[package]
name = "heartland-server"
version = "0.1.0"
authors = ["Jan Keith Darunday <jkcdarunday@gmail.com>"]

[dependencies]
iron="*"
router="*"
mount="*"
persistent="*"

redis="*"
r2d2="0.6"
r2d2_redis="*"
